
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: unicyber
      POSTGRES_DB: unicyber
    volumes: [ db-data:/var/lib/postgresql/data ]
    ports: ["5432:5432"]

  redis:
    ports: ["6379:6379"]

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: [ '9000:9000' ]

  api-gateway:
    build: ./services/api-gateway
    env_file: .env
    ports: ['8000:8000']
    depends_on: [db, redis, minio]
    volumes:
      - ./services/api-gateway/app:/app/app

  celery:
    build: ./services/celeryworker
    env_file: .env
    depends_on: [redis, db, api-gateway]
    command: ["celery", "-A", "app.tasks.celery", "worker", "--loglevel=info"]
    volumes:
      - ./services/api-gateway/app:/app/app

  scanner:
    build: ./services/scanners
    env_file: .env
    depends_on: [redis, db]
    command: ["python", "worker.py"]
    volumes:
      - ./services/scanners:/app

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis

  web:
    build: ./web
    ports: [ '3000:3000' ]
    env_file: .env
    depends_on: [api-gateway]

volumes:
  db-data:
